[cursor]
style = { shape = "Beam", blinking = "On" }

[font]
normal = { family = "FiraCode Nerd Font" }
bold = { family = "FiraCode NerdFont" }
size = 14.0

[mouse]
bindings = [
{ mouse = "Right", mods = "Control", action = "Paste" },
]

[selection]
save_to_clipboard = true
